/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staticsync;

class Bracket{
    synchronized static public void generate(String threadCode){
    for(int i =0; i<=10; i++){
        if(i<=5){
            System.out.print("[");
        }
        else{System.out.print("]");
        }
    }System.out.println("Generated by thread "+threadCode);
    
    }
}
public class StaticSync {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        new Thread(new Runnable(){
            @Override
            public void run() {
                   for(int i = 0; i<=5; i++){
                   Bracket.generate("thread 1");
                   }
            }
        }).start();
        
         new Thread(new Runnable(){
            @Override
            public void run() {
                   for(int i = 0; i<=5; i++){
                   Bracket.generate("thread 2");
                   }
            }
        }).start();
       
    
    }
    
}
